name: flutter_gifimage
description: A gif image package for Flutter that allows control of GIF speed and progress.
version: 1.2.1
homepage: https://github.com/peng8350/flutter_gifimage

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
